"""add finding report fields

Revision ID: 0c11d25e9cb6
Revises: a1b2c3d4e5f6
Create Date: 2026-08-29 18:47:12.418885

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0c11d25e9cb6'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('findings', sa.Column('affected', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('cvss_score', sa.Float(), nullable=True))
    op.add_column('findings', sa.Column('cvss_vector', sa.String(length=128), nullable=True))
    op.add_column('findings', sa.Column('cves', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('known_exploits', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('remediation', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('references', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'references')
    op.drop_column('findings', 'remediation')
    op.drop_column('findings', 'known_exploits')
    op.drop_column('findings', 'cves')
    op.drop_column('findings', 'cvss_vector')
    op.drop_column('findings', 'cvss_score')
    op.drop_column('findings', 'affected')
    op.drop_column('findings', 'category')
    # ### end Alembic commands ###
